server:
  port: ${PORT:8085}

spring:
  application:
    name: book-my-ticket

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/book-my-ticket?createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:Naveen@1103}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        '[format_sql]': false

  data:
    redis:
      url: ${SPRING_REDIS_URL:redis://localhost:6379}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:smsiddu2266@gmail.com}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

admin:
  email: ${ADMIN_EMAIL:admin@gmail.com}
  password: ${ADMIN_PASSWORD:admin}

cloudinary:
  url: ${CLOUDINARY_URL}